name: Deploy to GCP VM

on:
  push:
    branches:
      - master # trigger manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.GCP_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Deploy to GCP VM
      env:
        GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
        GCP_VM_USER: ${{ secrets.GCP_VM_USER }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        # SSH into the VM and execute deployment commands
        ssh $GCP_VM_USER@$GCP_VM_IP << 'EOF'
          # Navigate to project directory
          cd $PROJECT_PATH

          # Pull latest changes
          git pull origin main

          # Make install script executable
          chmod +x install.sh

          # Run install script
          ./install.sh

          # Kill existing bot process if running
          pkill -f "planner_bot.py" || true

          # Activate virtual environment and start bot in background
          source .venv/bin/activate
          nohup python3 tm_bot/planner_bot.py > bot.log 2>&1 &

          # Exit SSH session
          exit
        EOF 